_target_: birdclef2024.models.baseline.SmallBaselineModel
weights: ${const:torchvision.models.EfficientNet_B0_Weights.IMAGENET1K_V1}
num_classes: ${const:audyn.utils.data.birdclef.birdclef2024.num_primary_labels}
