_target_: birdclef2024.models.baseline.BaselineModel.build_from_pretrained
pretrained_model_name_or_path: ${train.resume.checkpoint}
num_classes: ${const:audyn.utils.data.birdclef.birdclef2024.num_primary_labels}
