_target_: birdclef2024.models.baseline.BaselineModel.build_from_pretrained
pretrained_model_name_or_path: ${train.resume.checkpoint}
num_classes: ${const:birdclef2024.utils.data.num_birdclef2024_pretrain_primary_labels}
