train:
  _target_: birdclef2024.utils.data.BirdCLEF2024PrimaryLabelMultiWebDataset
  list_path:
  feature_dir:
  shuffle: true
validation:
  _target_: birdclef2024.utils.data.BirdCLEF2024PrimaryLabelMultiWebDataset
  list_path:
  feature_dir:
  shuffle: false
