train:
  _target_: birdclef2024.utils.data.BirdCLEF2024PrimaryLabelMultiWebDataset
  list_path:
  feature_dir:
  audio_key: audio
  sample_rate_key: sample_rate
  label_name_key: primary_label
  filename_key: filename
  shuffle: true
validation:
  _target_: birdclef2024.utils.data.BirdCLEF2024PrimaryLabelMultiWebDataset
  list_path:
  feature_dir:
  audio_key: ${..train.audio_key}
  sample_rate_key: ${..train.sample_rate_key}
  label_name_key: ${..train.label_name_key}
  filename_key: ${..train.filename_key}
  shuffle: false
